name: portfolio
on:
    push:
        branches: [main]
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            #get access to your portfolio code via pre built actions
            # clones or checks out the code where this workflow is written
            - name: checkout the code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run Python file
              run: |
                  python app.py
              # setup github pages

            - name: setup github pages
              uses: actions/configure-pages@v5

              # static code artifacts  - to load faster taki load balance kr sake
            - name: upload static files
              uses: actions/upload-pages-artifact@v4
              
              # deploy code

            - name: diploy to github pages
              id: deployment
              uses: actions/deploy-pages@v4  

